name: VAMSI Market News Bot

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  news-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Market News Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python alert_bot.py

      - name: Save news history
        run: |
          git config user.name "VAMSI News Bot"
          git config user.email "actions@github.com"

          git add sent_news.txt

          git diff --cached --quiet || git commit -m "Update news history"

          git push
