name: Market Alert Bot

on:
  schedule:
    - cron: "*/25 * * * *"
  workflow_dispatch:

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - name: Download bot
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Run alert bot
        env:
          TWELVE_API_KEY: ${{ secrets.TWELVE_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python alert_bot.py
